# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://shreyakhurana.github.io
baseurl: /
title: Shreya Khurana
author: Shreya Khurana
description: Personal blog and resume
avatar: shreya.png
email: shreyak4@illinois.edu
github: ShreyaKhurana # username
#twitter: username
linkedin: Shreya-Khurana
email_full: mailto:shreyak4@illinois.edu
website: shreyakhurana.github.io
website_full: https://shreyakhurana.github.io
github: ShreyaKhurana
twitter: twitter
tel:
tel_full:
google_maps:
address:
  street:
  postcode:
  city:
  country:
google_analytics:

# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
